# Inflation in Italy

AIM: show which datasets are available for inflation in Italy, by ISTAT.

In [3]:
import warnings 
from istatapi import discovery, retrieval
import requests

warnings.filterwarnings('ignore')
requests.urllib3.disable_warnings()

! pip show istatapi

Name: istatapi
Version: 1.0.0
Summary: Python API for ISTAT (The Italian National Institute of Statistics)
Home-page: https://github.com/Attol8/istatapi
Author: Jacopo Attolini
Author-email: jacopoattolini@gmail.com
License: Apache Software License 2.0
Location: /Users/danieleongari/opt/anaconda3/envs/py312/lib/python3.12/site-packages
Requires: fastcore, matplotlib, pandas, pyopenssl, requests
Required-by:

In [4]:
all_datasets = discovery.search_dataset("")
display(all_datasets)

,df_id,version,df_description,df_structure_id
0,101_1015,1.3,Crops,DCSP_COLTIVAZIONI
1,101_1030,1.0,"PDO, PGI and TSG quality products",DCSP_DOPIGP
2,101_1033,1.0,slaughtering,DCSP_MACELLAZIONI
3,101_1039,1.2,Agritourism - municipalities,DCSP_AGRITURISMO_COM
4,101_1077,1.0,"PDO, PGI and TSG products: operators - munici...",DCSP_DOPIGP_COM
...,...,...,...,...
504,97_953,1.1,Environmental protection expenditure,DCCN_SPESAPROTAMB
505,98_1066,1.0,Productivity measures - Accounts in the 2014 v...,DCCN_PRODUTTIVITA_B14
506,98_1067,1.0,Productivity measures - Accounts in the 2011 v...,DCCN_PRODUTTIVITA_B11
507,98_197,1.3,Productivity measures,DCCN_PRODUTTIVITA
508,9_951,1.3,Mining and quarrying,DCCV_CAVE_MIN

In [15]:
selected_datasets = (
    all_datasets
    .query('df_description.str.contains("hicp|nic|foi", case=False)')
    .query('~df_description.str.contains("municipal|polytechnic|communic", case=False)')
    .sort_values('df_structure_id', ascending=True)
)

count=0
for _, row in selected_datasets.iterrows():
    print(f'{count+1:2d} - v{row["version"]} {row["df_structure_id"]}  - {row["df_description"]}')
    count+=1

 1 - v1.1 DCSP_FOI1  - Foi - monthly data until 2010 (base 1995)
 2 - v1.0 DCSP_FOI1B2010  - Foi - monthly data from 2011 to 2015 (base 2010)
 3 - v1.1 DCSP_FOI1B2015  - Foi - monthly data from 2016 (base 2015)
 4 - v1.1 DCSP_FOI2  - Foi - annual data until 2010 (base 1995)
 5 - v1.0 DCSP_FOI2B2010  - Foi - annual data from 2011 to 2015  (base 2010)
 6 - v1.0 DCSP_FOI2B2015  - Foi - annual data from 2016 (base 2015)
 7 - v1.0 DCSP_FOI3B2010  - FOI - Weights from 2011 to 2015
 8 - v1.1 DCSP_FOI3B2015  - FOI - Weights from 2016 onwards
 9 - v1.0 DCSP_IPCA1  - Hicp - monthly and quarterly data from 2001 until 2015(base 2005)
10 - v1.4 DCSP_IPCA1B2015  - Hicp - monthly data from 2001
11 - v1.1 DCSP_IPCA2  - Hicp - annual data from 2001 until 2015 (base 2005)
12 - v1.2 DCSP_IPCA2B2015  - Hicp - annual data from 2001 (base 2015)
13 - v1.2 DCSP_IPCA3  - Hicp - weights  from 2001
14 - v1.2 DCSP_IPCATC1  - Hicp - at constant tax rates monthly data (base 2005)
15 - v1.4 DCSP_IPCATC1B2015  - Hicp - at constant tax rates monthly data (base 2015)
16 - v1.1 DCSP_IPCATC2  - Hicp - at constant tax rates annual data(base 2005)
17 - v1.1 DCSP_IPCATC2B2015  - Hicp- at constant tax rates annual data (base 2015)
18 - v1.9 DCSP_NIC1B2015  - Nic - monthly data from 2016 onwards(base 2015)
19 - v1.4 DCSP_NIC2B2015  - Nic – annual average from 2016 onwards(base 2015)
20 - v1.6 DCSP_NIC3B2015  - Nic – weights from 2016
21 - v1.1 DCSP_NICDUE  - Nic - annual data until 2010
22 - v1.0 DCSP_NICDUEB2010  - Nic - annual average from 2011 until 2015 (base 2010)
23 - v1.1 DCSP_NICTRE  - Nic - weights  until 2010
24 - v1.0 DCSP_NICTREB2010  - Nic – weights from 2011 until 2015
25 - v1.1 DCSP_NICUNOB  - Nic - monthly data until 2010
26 - v1.4 DCSP_NICUNOBB2010  - Nic - monthly data from 2011 until 2015 (base 2010)
27 - v1.0 SEP_PREZZI_NIC_FOI_WEIGHT_2010  - Foi – weights until 2010

In [18]:
interesting_dss = ["DCSP_IPCA1B2015", "DCSP_FOI1B2015", "DCSP_NICUNOB", "DCSP_NICUNOBB2010", "DCSP_NIC1B2015"] 

for ds_structure_id in interesting_dss:
    print(f"\n############ {ds_structure_id} ################################################################")
    print("Description:", all_datasets.query(f'df_structure_id == "{ds_structure_id}"').iloc[0].df_description)
    print(f"Website: http://dati.istat.it/Index.aspx?DataSetCode={ds_structure_id}")
    try:
        ds = discovery.DataSet(dataflow_identifier=ds_structure_id)
        ds_info = ds.dimensions_info()
        display(ds_info)
        for col in ds_info.dimension:
            print(f" >> {col}")
            display(ds.get_dimension_values(col).sort_values("values_ids").reset_index(drop=True))
            
    except Exception as e:
        print("Error:", e)
        continue

############ DCSP_IPCA1B2015 ################################################################
Description: Hicp - monthly data from 2001
Website: http://dati.istat.it/Index.aspx?DataSetCode=DCSP_IPCA1B2015

     dimension    dimension_ID  description
0         FREQ         CL_FREQ    Frequency
1      MISURA1      CL_MISURA1      MISURA1
2     IND_TYPE   CL_TIPO_DATO2  Data type 2
3  COICOP_IPCA  CL_COICOP_2015  Coicop 2015
4     ITTER107     CL_ITTER107    Territory

 >> FREQ

  values_ids values_description
0          A             annual
1          M            monthly

 >> MISURA1

  values_ids                                 values_description
0          4                                       index number
1          6          percentage changes on the previous period
2          7  percentage changes on the same period of the p...
3          8                      annual average rate of change

 >> IND_TYPE

  values_ids                                 values_description
0         41  harmonized index of consumer prices (base 2015...
1         43  harmonized index of consumer prices for expend...
2         44  harmonized index of consumer prices for expend...
3         45  harmonized index of consumer prices for expend...
4         46  harmonized index of consumer prices for expend...
5         47  harmonized index of consumer prices for expend...
6         48  harmonized index of consumer prices for expend...

 >> COICOP_IPCA

          values_ids                                 values_description
0                 00                                          all items
1               00XE                     overall index excluding energy
2           00XEFOOD  overall index excluding energy, food, alcohol ...
3        00XEFOODUNP  overall index excluding energy and unprocessed...
4    00XEFOODUNP_5DG  overall index excluding energy and unprocessed...
..               ...                                                ...
410           SERVRP  services related to recreation, including repa...
411       SERVRP_5DG  services related to recreation, including repa...
412        SERVTRANS                      services related to transport
413    SERVTRANS_5DG     services related to transport (5-digit detail)
414         SERV_5DG  -- services (overall index excluding goods) (5...

[415 rows x 2 columns]

 >> ITTER107

  values_ids values_description
0         IT              Italy

############ DCSP_FOI1B2015 ################################################################
Description: Foi - monthly data from 2016 (base 2015)
Website: http://dati.istat.it/Index.aspx?DataSetCode=DCSP_FOI1B2015

          dimension    dimension_ID  description
0              FREQ         CL_FREQ    Frequency
1  COICOP_REV_ISTAT  CL_COICOP_2015  Coicop 2015
2          ITTER107     CL_ITTER107    Territory
3           MISURA1      CL_MISURA1      MISURA1
4          IND_TYPE   CL_TIPO_DATO2  Data type 2

 >> FREQ

  values_ids values_description
0          M            monthly

 >> COICOP_REV_ISTAT

   values_ids                                 values_description
0          00                                          all items
1        00ST                         all items excluded tobacco
2          01                -- food and non-alcoholic beverages
3          02                 -- alcoholic beverages and tobacco
4          03                           -- clothing and footwear
5          04  -- housing, water, electricity, gas and other ...
6          05  -- furnishings, household equipment and routin...
7          06                                          -- health
8          07                                       -- transport
9          08                                   -- communication
10         09                          -- recreation and culture
11         10                                       -- education
12         11                          -- restaurants and hotels
13         12                -- miscellaneous goods and services
14        OR0                                        COICOP_2015
15        OR1                                   Product typology
16        OR2         Administered and non-administered products
17        OR3                                 Purchase frequency

 >> ITTER107

    values_ids values_description
0           IT              Italy
1         ITC1           Piemonte
2        ITC11             Torino
3        ITC12           Vercelli
4        ITC13             Biella
..         ...                ...
117      ITG25            Sassari
118      ITG26              Nuoro
119      ITG27           Cagliari
120      ITG28           Oristano
121      ITG29       Olbia-Tempio

[122 rows x 2 columns]

 >> MISURA1

  values_ids                                 values_description
0          4                                       index number
1          6          percentage changes on the previous period
2          7  percentage changes on the same period of the p...

 >> IND_TYPE

  values_ids                                 values_description
0         55  indice dei prezzi al consumo per le famiglie d...

############ DCSP_NICUNOB ################################################################
Description: Nic - monthly data until 2010
Website: http://dati.istat.it/Index.aspx?DataSetCode=DCSP_NICUNOB

    dimension   dimension_ID  description
0        FREQ        CL_FREQ    Frequency
1  COICOP_NIC  CL_COICOP_NIC   COICOP NIC
2    ITTER107    CL_ITTER107    Territory
3     MISURA1     CL_MISURA1      MISURA1
4    IND_TYPE  CL_TIPO_DATO2  Data type 2

 >> FREQ

  values_ids values_description
0          M            monthly

 >> COICOP_NIC

      values_ids                                 values_description
0             00                                          all items
1           00ST                      all items (excluding tobacco)
2           00XE                     overall index excluding energy
3    00XEFOODUNP  overall index excluding energy and unprocessed...
4             01                -- food and non-alcoholic beverages
..           ...                                                ...
351     SERVMISC                           services - miscellaneous
352       SERVRP  services related to recreation, including repa...
353    SERVTRANS                      services related to transport
354     SERVXAPS             services excluding administered prices
355        TOBAC                                            tobacco

[356 rows x 2 columns]

 >> ITTER107

    values_ids values_description
0           IT              Italy
1          ITC         Nord-ovest
2         ITC1           Piemonte
3        ITC11             Torino
4        ITC12           Vercelli
..         ...                ...
114      ITG17            Catania
115      ITG19           Siracusa
116       ITG2           Sardegna
117      ITG25            Sassari
118      ITG27           Cagliari

[119 rows x 2 columns]

 >> MISURA1

  values_ids                                 values_description
0          4                                       index number
1          6          percentage changes on the previous period
2          7  percentage changes on the same period of the p...

 >> IND_TYPE

  values_ids                                 values_description
0          1  consumer price index for the whole nation (bas...
1          7  consumer price index for the whole nation (bas...
2          9  consumer price index for the whole nation (bas...

############ DCSP_NICUNOBB2010 ################################################################
Description: Nic - monthly data from 2011 until 2015 (base 2010)
Website: http://dati.istat.it/Index.aspx?DataSetCode=DCSP_NICUNOBB2010

          dimension   dimension_ID  description
0              FREQ        CL_FREQ    Frequency
1          ITTER107    CL_ITTER107    Territory
2           MISURA1     CL_MISURA1      MISURA1
3          IND_TYPE  CL_TIPO_DATO2  Data type 2
4  COICOP_REV_ISTAT      CL_COICOP       COICOP

 >> FREQ

  values_ids values_description
0          M            monthly

 >> ITTER107

    values_ids values_description
0           IT              Italy
1          ITC         Nord-ovest
2         ITC1           Piemonte
3        ITC11             Torino
4        ITC12           Vercelli
..         ...                ...
109      ITG17            Catania
110      ITG19           Siracusa
111       ITG2           Sardegna
112      ITG25            Sassari
113      ITG27           Cagliari

[114 rows x 2 columns]

 >> MISURA1

  values_ids                                 values_description
0          4                                       index number
1          6          percentage changes on the previous period
2          7  percentage changes on the same period of the p...

 >> IND_TYPE

  values_ids                                 values_description
0          9  indice dei prezzi al consumo per l'intera coll...

 >> COICOP_REV_ISTAT

    values_ids                                 values_description
0           00                                          all items
1         00ST                         all items excluded tobacco
2        00XAP         -- all-items excluding administered prices
3         00XE                     overall index excluding energy
4     00XEFOOD  overall index excluding energy, food, alcohol ...
..         ...                                                ...
759   SERVMISC                           services - miscellaneous
760     SERVRP  services related to recreation, including repa...
761  SERVTRANS                      services related to transport
762   SERVXAPS             services excluding administered prices
763      TOBAC                                            tobacco

[764 rows x 2 columns]

############ DCSP_NIC1B2015 ################################################################
Description: Nic - monthly data from 2016 onwards(base 2015)
Website: http://dati.istat.it/Index.aspx?DataSetCode=DCSP_NIC1B2015

          dimension    dimension_ID  description
0              FREQ         CL_FREQ    Frequency
1  COICOP_REV_ISTAT  CL_COICOP_2015  Coicop 2015
2          ITTER107     CL_ITTER107    Territory
3           MISURA1      CL_MISURA1      MISURA1
4          IND_TYPE   CL_TIPO_DATO2  Data type 2

 >> FREQ

  values_ids values_description
0          M            monthly

 >> COICOP_REV_ISTAT

    values_ids                                 values_description
0           00                                          all items
1         00ST                         all items excluded tobacco
2        00XAP         -- all-items excluding administered prices
3         00XE                     overall index excluding energy
4     00XEFOOD  overall index excluding energy, food, alcohol ...
..         ...                                                ...
742   SERVMISC                           services - miscellaneous
743     SERVRP  services related to recreation, including repa...
744  SERVTRANS                      services related to transport
745   SERVXAPS             services excluding administered prices
746      TOBAC                                            tobacco

[747 rows x 2 columns]

 >> ITTER107

    values_ids values_description
0           IT              Italy
1          ITC         Nord-ovest
2         ITC1           Piemonte
3        ITC11             Torino
4        ITC12           Vercelli
..         ...                ...
122      ITG25            Sassari
123      ITG26              Nuoro
124      ITG27           Cagliari
125      ITG28           Oristano
126      ITG29       Olbia-Tempio

[127 rows x 2 columns]

 >> MISURA1

  values_ids                                 values_description
0          4                                       index number
1          6          percentage changes on the previous period
2          7  percentage changes on the same period of the p...

 >> IND_TYPE

  values_ids                                 values_description
0         39  consumer price index for the whole nation (bas...
1          9  consumer price index for the whole nation (bas...